### ISSUE TITLE
Menubar still bright

### ISSUE THREAD

**Issue by confuso** [p-e-w/GTKDarkThemeVariantSetter#6]
Hi,
I'm using Build 3095 on ArchLinux with Gnome 3.18.3. After installing xorg-utils, the window is turning dark, but unfortunately the menu bar stays bright. You're hiding your menu bar in the screenshots, so probably there's no workaround for that?

Best regards
confuso

**Comment by piqus** [comment]
tl;dr Yes

**Comment by piqus** [comment]
Edited post.

**Comment by p-e-w** [comment]
This is impossible to fix because Sublime Text uses GTK+ 2, which does not support dark themes so only the title bar will change color, not any of the UI elements including the menu bar.
